name: Test Linter

on:
  push:
      branches:
        - '**'
      tags:
        - '**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
      - name: Run Lint
        run: |
          poetry install
          poetry run flake8 brain_games
