name: Test Linter

on:
  push:
      branches:
        - '**'
      tags:
        - '**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install python
        uses: actions/setup-puthon@v2
        with:
          python-version: 3.8
      - name: Install
        run: make install
      - name: Run Lint
        run: make lint
